# Install

1) Install Anaconda Python https://www.anaconda.com/download/ (check “add to path”)

2) Install OpenAI Gym

```pip install gym```

3) Launch Jupyter Notebook

```jupyter notebook```

4) Try Gym https://gym.openai.com/docs/

*) THIS NOTEBOOK: https://github.com/jurgisp/nma-2018-rl /openai-sandbox.ipynb

# Run

In [2]:
# https://gym.openai.com/docs/

import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[0.01222993 0.01659172 0.03067565 0.01905395]
[ 0.01256177  0.21126063  0.03105673 -0.26379481]
[ 0.01678698  0.40592584  0.02578083 -0.54652261]
[ 0.0249055   0.60067626  0.01485038 -0.83097244]
[ 0.03691902  0.40535452 -0.00176907 -0.53365629]
[ 0.04502611  0.21025749 -0.0124422  -0.24153131]
[ 0.04923126  0.01531546 -0.01727282  0.04720119]
[ 0.04953757 -0.1795546  -0.0163288   0.33438473]
[ 0.04594648  0.01579589 -0.0096411   0.03659759]
[ 0.0462624   0.21105476 -0.00890915 -0.25911154]
[ 0.05048349  0.01606113 -0.01409138  0.03074806]
[ 0.05080472  0.21138229 -0.01347642 -0.26634733]
[ 0.05503236  0.01645524 -0.01880337  0.02205474]
[ 0.05536147 -0.17839207 -0.01836227  0.30874618]
[ 0.05179362  0.01698664 -0.01218735  0.01032932]
[ 0.05213336 -0.17795843 -0.01198076  0.29914221]
[ 0.04857419  0.01733223 -0.00599792  0.00270499]
[ 0.04892083 -0.17770319 -0.00594382  0.29348948]
[ 4.5

[ 0.03797654 -0.03373478 -0.01845192 -0.02106797]
[ 0.03730185  0.16164687 -0.01887328 -0.3195151 ]
[ 0.04053478 -0.03320128 -0.02526358 -0.03284334]
[ 0.03987076  0.16227368 -0.02592045 -0.33338892]
[ 0.04311623  0.35775479 -0.03258823 -0.63413184]
[ 0.05027133  0.1631022  -0.04527086 -0.35188724]
[ 0.05353337 -0.03134771 -0.05230861 -0.07381629]
[ 0.05290642 -0.22568225 -0.05378493  0.2019151 ]
[ 0.04839277 -0.02983399 -0.04974663 -0.10723764]
[ 0.04779609  0.16596424 -0.05189139 -0.41519113]
[ 0.05111538  0.36178179 -0.06019521 -0.72377129]
[ 0.05835101  0.16754173 -0.07467063 -0.45062562]
[ 0.06170185 -0.02644909 -0.08368315 -0.18238301]
[ 0.06117287  0.16976438 -0.08733081 -0.50024742]
[ 0.06456815 -0.0240249  -0.09733575 -0.2363139 ]
[ 0.06408766 -0.21763122 -0.10206203  0.02414941]
[ 0.05973503 -0.02120494 -0.10157904 -0.29891092]
[ 0.05931093 -0.21474332 -0.10755726 -0.03991271]
[ 0.05501607 -0.40817168 -0.10835552  0.21699227]
[ 0.04685263 -0.60159124 -0.10401567  0.47362587]


KeyboardInterrupt: 

# Step-by-step

In [23]:
# https://gym.openai.com/docs/
import gym

In [13]:
# Create environment. 
env = gym.make('CartPole-v0')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [53]:
# env.reset() returns state 
# 4d array corresponds to [position, velocity, angle, angular velocity]
env.reset()

array([-0.02365317, -0.04622913, -0.04186527,  0.04925874])

In [86]:
# env.step(action) - performs a step
# Returns (state, reward, done, extra)

(state, reward, done, _) = env.step(1)

print(state)
print(reward)
print(done)

[-0.33730283573424674, -1.2245550925685451, 0.3982525381953646, 2.121940847114506]
0.0
True


In [14]:
# Can draw environment in UI (a bit buggy)
env.render()

In [15]:
# This closes the rendered UI window
env.close()

# Simple agent

In [35]:
import gym

def run_episode():
    env = gym.make('CartPole-v0')
    state = env.reset()
    steps = 0
    
    while True:
        env.render()
        
        [x, vx, a, va] = state
        action = 0 if a < 0 else 1
        
        (state, reward, done, _) = env.step(action)
        steps += 1
        if done:
            break
            
    env.close()
    print('Finished in %s steps' % steps)

In [36]:
run_episode()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Finished in 62 steps
